// Mocks generated by Mockito 5.4.6 from annotations
// in flax/test/metadata_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i15;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i13;

import 'package:file/file.dart' as _i3;
import 'package:flax/domain/enums.dart' as _i8;
import 'package:flax/domain/models/models.dart' as _i2;
import 'package:flax/domain/repositories/library_repository.dart' as _i10;
import 'package:flax/services/database/library_dao.dart' as _i9;
import 'package:flax/services/subsonic/subsonic_client.dart' as _i6;
import 'package:flutter_cache_manager/src/cache_managers/base_cache_manager.dart'
    as _i11;
import 'package:flutter_cache_manager/src/result/file_info.dart' as _i4;
import 'package:flutter_cache_manager/src/result/file_response.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeServer_0 extends _i1.SmartFake implements _i2.Server {
  _FakeServer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArtist_1 extends _i1.SmartFake implements _i2.Artist {
  _FakeArtist_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAlbum_2 extends _i1.SmartFake implements _i2.Album {
  _FakeAlbum_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSong_3 extends _i1.SmartFake implements _i2.Song {
  _FakeSong_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchResult_4 extends _i1.SmartFake implements _i2.SearchResult {
  _FakeSearchResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_5 extends _i1.SmartFake implements Uri {
  _FakeUri_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlaylist_6 extends _i1.SmartFake implements _i2.Playlist {
  _FakePlaylist_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_7 extends _i1.SmartFake implements _i3.File {
  _FakeFile_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileInfo_8 extends _i1.SmartFake implements _i4.FileInfo {
  _FakeFileInfo_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_9 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystem_10 extends _i1.SmartFake implements _i3.FileSystem {
  _FakeFileSystem_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_11 extends _i1.SmartFake implements _i3.Directory {
  _FakeDirectory_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_12 extends _i1.SmartFake
    implements _i3.FileSystemEntity {
  _FakeFileSystemEntity_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_13 extends _i1.SmartFake implements _i5.FileStat {
  _FakeFileStat_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_14 extends _i1.SmartFake
    implements _i5.RandomAccessFile {
  _FakeRandomAccessFile_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_15 extends _i1.SmartFake implements _i5.IOSink {
  _FakeIOSink_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubsonicClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubsonicClient extends _i1.Mock implements _i6.SubsonicClient {
  @override
  _i2.Server get server =>
      (super.noSuchMethod(
            Invocation.getter(#server),
            returnValue: _FakeServer_0(this, Invocation.getter(#server)),
            returnValueForMissingStub: _FakeServer_0(
              this,
              Invocation.getter(#server),
            ),
          )
          as _i2.Server);

  @override
  _i7.Future<bool> ping() =>
      (super.noSuchMethod(
            Invocation.method(#ping, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String?> tryPing() =>
      (super.noSuchMethod(
            Invocation.method(#tryPing, []),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, int>> getOpenSubsonicExtensions() =>
      (super.noSuchMethod(
            Invocation.method(#getOpenSubsonicExtensions, []),
            returnValue: _i7.Future<Map<String, int>>.value(<String, int>{}),
            returnValueForMissingStub: _i7.Future<Map<String, int>>.value(
              <String, int>{},
            ),
          )
          as _i7.Future<Map<String, int>>);

  @override
  _i7.Future<List<_i2.Artist>> getArtists() =>
      (super.noSuchMethod(
            Invocation.method(#getArtists, []),
            returnValue: _i7.Future<List<_i2.Artist>>.value(<_i2.Artist>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Artist>>.value(
              <_i2.Artist>[],
            ),
          )
          as _i7.Future<List<_i2.Artist>>);

  @override
  _i7.Future<_i2.Artist> getArtist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArtist, [id]),
            returnValue: _i7.Future<_i2.Artist>.value(
              _FakeArtist_1(this, Invocation.method(#getArtist, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Artist>.value(
              _FakeArtist_1(this, Invocation.method(#getArtist, [id])),
            ),
          )
          as _i7.Future<_i2.Artist>);

  @override
  _i7.Future<List<_i2.Album>> getArtistAlbums(String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistAlbums, [artistId]),
            returnValue: _i7.Future<List<_i2.Album>>.value(<_i2.Album>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Album>>.value(
              <_i2.Album>[],
            ),
          )
          as _i7.Future<List<_i2.Album>>);

  @override
  _i7.Future<_i2.Album> getAlbum(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbum, [id]),
            returnValue: _i7.Future<_i2.Album>.value(
              _FakeAlbum_2(this, Invocation.method(#getAlbum, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Album>.value(
              _FakeAlbum_2(this, Invocation.method(#getAlbum, [id])),
            ),
          )
          as _i7.Future<_i2.Album>);

  @override
  _i7.Future<List<_i2.Song>> getAlbumSongs(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumSongs, [albumId]),
            returnValue: _i7.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i7.Future<List<_i2.Song>>);

  @override
  _i7.Future<_i2.Song> getSong(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSong, [id]),
            returnValue: _i7.Future<_i2.Song>.value(
              _FakeSong_3(this, Invocation.method(#getSong, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Song>.value(
              _FakeSong_3(this, Invocation.method(#getSong, [id])),
            ),
          )
          as _i7.Future<_i2.Song>);

  @override
  _i7.Future<List<String>> getGenres() =>
      (super.noSuchMethod(
            Invocation.method(#getGenres, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i2.Album>> getAlbumList(
    _i8.AlbumListType? type, {
    int? offset = 0,
    int? count = 20,
    int? fromYear,
    int? toYear,
    String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAlbumList,
              [type],
              {
                #offset: offset,
                #count: count,
                #fromYear: fromYear,
                #toYear: toYear,
                #genre: genre,
              },
            ),
            returnValue: _i7.Future<List<_i2.Album>>.value(<_i2.Album>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Album>>.value(
              <_i2.Album>[],
            ),
          )
          as _i7.Future<List<_i2.Album>>);

  @override
  _i7.Future<_i2.SearchResult> search(
    String? query, {
    int? artistCount = 20,
    int? albumCount = 20,
    int? songCount = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [query],
              {
                #artistCount: artistCount,
                #albumCount: albumCount,
                #songCount: songCount,
              },
            ),
            returnValue: _i7.Future<_i2.SearchResult>.value(
              _FakeSearchResult_4(
                this,
                Invocation.method(
                  #search,
                  [query],
                  {
                    #artistCount: artistCount,
                    #albumCount: albumCount,
                    #songCount: songCount,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i2.SearchResult>.value(
              _FakeSearchResult_4(
                this,
                Invocation.method(
                  #search,
                  [query],
                  {
                    #artistCount: artistCount,
                    #albumCount: albumCount,
                    #songCount: songCount,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i2.SearchResult>);

  @override
  Uri getStreamUri(String? songId, {int? maxBitRate, String? format}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getStreamUri,
              [songId],
              {#maxBitRate: maxBitRate, #format: format},
            ),
            returnValue: _FakeUri_5(
              this,
              Invocation.method(
                #getStreamUri,
                [songId],
                {#maxBitRate: maxBitRate, #format: format},
              ),
            ),
            returnValueForMissingStub: _FakeUri_5(
              this,
              Invocation.method(
                #getStreamUri,
                [songId],
                {#maxBitRate: maxBitRate, #format: format},
              ),
            ),
          )
          as Uri);

  @override
  Uri getCoverArtUri(String? id, {int? size}) =>
      (super.noSuchMethod(
            Invocation.method(#getCoverArtUri, [id], {#size: size}),
            returnValue: _FakeUri_5(
              this,
              Invocation.method(#getCoverArtUri, [id], {#size: size}),
            ),
            returnValueForMissingStub: _FakeUri_5(
              this,
              Invocation.method(#getCoverArtUri, [id], {#size: size}),
            ),
          )
          as Uri);

  @override
  _i7.Future<String?> getLyrics({String? artist, String? title}) =>
      (super.noSuchMethod(
            Invocation.method(#getLyrics, [], {#artist: artist, #title: title}),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i2.Lyrics?> getSongLyrics(String? songId) =>
      (super.noSuchMethod(
            Invocation.method(#getSongLyrics, [songId]),
            returnValue: _i7.Future<_i2.Lyrics?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.Lyrics?>.value(),
          )
          as _i7.Future<_i2.Lyrics?>);

  @override
  _i7.Future<void> star({String? id, String? albumId, String? artistId}) =>
      (super.noSuchMethod(
            Invocation.method(#star, [], {
              #id: id,
              #albumId: albumId,
              #artistId: artistId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unstar({String? id, String? albumId, String? artistId}) =>
      (super.noSuchMethod(
            Invocation.method(#unstar, [], {
              #id: id,
              #albumId: albumId,
              #artistId: artistId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.SearchResult> getStarred() =>
      (super.noSuchMethod(
            Invocation.method(#getStarred, []),
            returnValue: _i7.Future<_i2.SearchResult>.value(
              _FakeSearchResult_4(this, Invocation.method(#getStarred, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.SearchResult>.value(
              _FakeSearchResult_4(this, Invocation.method(#getStarred, [])),
            ),
          )
          as _i7.Future<_i2.SearchResult>);

  @override
  _i7.Future<void> setRating(String? id, int? rating) =>
      (super.noSuchMethod(
            Invocation.method(#setRating, [id, rating]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> scrobble(String? id, {bool? submission = true}) =>
      (super.noSuchMethod(
            Invocation.method(#scrobble, [id], {#submission: submission}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.Playlist>> getPlaylists() =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylists, []),
            returnValue: _i7.Future<List<_i2.Playlist>>.value(<_i2.Playlist>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Playlist>>.value(
              <_i2.Playlist>[],
            ),
          )
          as _i7.Future<List<_i2.Playlist>>);

  @override
  _i7.Future<_i2.Playlist> getPlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylist, [id]),
            returnValue: _i7.Future<_i2.Playlist>.value(
              _FakePlaylist_6(this, Invocation.method(#getPlaylist, [id])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.Playlist>.value(
              _FakePlaylist_6(this, Invocation.method(#getPlaylist, [id])),
            ),
          )
          as _i7.Future<_i2.Playlist>);

  @override
  _i7.Future<List<_i2.Song>> getPlaylistSongs(String? playlistId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlaylistSongs, [playlistId]),
            returnValue: _i7.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i7.Future<List<_i2.Song>>);

  @override
  _i7.Future<void> createPlaylist({
    required String? name,
    List<String>? songIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlaylist, [], {
              #name: name,
              #songIds: songIds,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePlaylist(
    String? id, {
    String? name,
    String? comment,
    bool? public,
    List<String>? songIdsToAdd,
    List<int>? songIndexesToRemove,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePlaylist,
              [id],
              {
                #name: name,
                #comment: comment,
                #public: public,
                #songIdsToAdd: songIdsToAdd,
                #songIndexesToRemove: songIndexesToRemove,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deletePlaylist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlaylist, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> savePlayQueue(
    List<String>? songIds,
    String? currentId,
    int? positionMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePlayQueue, [songIds, currentId, positionMs]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.PlayQueue?> getPlayQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getPlayQueue, []),
            returnValue: _i7.Future<_i2.PlayQueue?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.PlayQueue?>.value(),
          )
          as _i7.Future<_i2.PlayQueue?>);

  @override
  _i7.Future<Map<String, dynamic>?> getScanStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getScanStatus, []),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> getArtistInfo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistInfo, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<_i2.ArtistInfo?> getArtistInfoParsed(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getArtistInfoParsed, [id]),
            returnValue: _i7.Future<_i2.ArtistInfo?>.value(),
            returnValueForMissingStub: _i7.Future<_i2.ArtistInfo?>.value(),
          )
          as _i7.Future<_i2.ArtistInfo?>);

  @override
  _i7.Future<List<_i2.Song>> getSimilarSongs(String? id, {int? count = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getSimilarSongs, [id], {#count: count}),
            returnValue: _i7.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i7.Future<List<_i2.Song>>);

  @override
  _i7.Future<List<_i2.Song>> getTopSongs(
    String? artistName, {
    int? count = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTopSongs, [artistName], {#count: count}),
            returnValue: _i7.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i7.Future<List<_i2.Song>>);

  @override
  _i7.Future<List<_i2.Song>> getRandomSongs({int? count = 20, String? genre}) =>
      (super.noSuchMethod(
            Invocation.method(#getRandomSongs, [], {
              #count: count,
              #genre: genre,
            }),
            returnValue: _i7.Future<List<_i2.Song>>.value(<_i2.Song>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Song>>.value(
              <_i2.Song>[],
            ),
          )
          as _i7.Future<List<_i2.Song>>);
}

/// A class which mocks [LibraryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryDao extends _i1.Mock implements _i9.LibraryDao {
  @override
  _i7.Stream<List<_i2.Artist>> watchArtists(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#watchArtists, [serverId]),
            returnValue: _i7.Stream<List<_i2.Artist>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Artist>>.empty(),
          )
          as _i7.Stream<List<_i2.Artist>>);

  @override
  _i7.Future<List<_i2.Artist>> getAllArtists(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllArtists, [serverId]),
            returnValue: _i7.Future<List<_i2.Artist>>.value(<_i2.Artist>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Artist>>.value(
              <_i2.Artist>[],
            ),
          )
          as _i7.Future<List<_i2.Artist>>);

  @override
  _i7.Stream<_i2.Artist?> watchArtist(String? serverId, String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#watchArtist, [serverId, artistId]),
            returnValue: _i7.Stream<_i2.Artist?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i2.Artist?>.empty(),
          )
          as _i7.Stream<_i2.Artist?>);

  @override
  _i7.Stream<List<_i2.Artist>> searchArtists(
    String? serverId,
    String? term,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchArtists, [serverId, term, limit]),
            returnValue: _i7.Stream<List<_i2.Artist>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Artist>>.empty(),
          )
          as _i7.Stream<List<_i2.Artist>>);

  @override
  _i7.Future<void> upsertArtists(List<_i2.Artist>? artists, DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#upsertArtists, [artists, now]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> artistsFetchedAt(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#artistsFetchedAt, [serverId]),
            returnValue: _i7.Future<DateTime?>.value(),
            returnValueForMissingStub: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Stream<_i2.Album?> watchAlbum(String? serverId, String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbum, [serverId, albumId]),
            returnValue: _i7.Stream<_i2.Album?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i2.Album?>.empty(),
          )
          as _i7.Stream<_i2.Album?>);

  @override
  _i7.Stream<List<_i2.Album>> watchArtistAlbums(
    String? serverId,
    String? artistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchArtistAlbums, [serverId, artistId]),
            returnValue: _i7.Stream<List<_i2.Album>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Album>>.empty(),
          )
          as _i7.Stream<List<_i2.Album>>);

  @override
  _i7.Stream<List<_i2.Album>> searchAlbums(
    String? serverId,
    String? term,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchAlbums, [serverId, term, limit]),
            returnValue: _i7.Stream<List<_i2.Album>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Album>>.empty(),
          )
          as _i7.Stream<List<_i2.Album>>);

  @override
  _i7.Stream<List<_i2.Album>> watchAlbumList(
    String? serverId,
    _i10.AlbumListQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbumList, [serverId, query]),
            returnValue: _i7.Stream<List<_i2.Album>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Album>>.empty(),
          )
          as _i7.Stream<List<_i2.Album>>);

  @override
  _i7.Stream<List<_i2.Album>> watchAlbumsByIds(
    String? serverId,
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbumsByIds, [serverId, ids]),
            returnValue: _i7.Stream<List<_i2.Album>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Album>>.empty(),
          )
          as _i7.Stream<List<_i2.Album>>);

  @override
  _i7.Stream<List<_i2.Album>> watchAllAlbums(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllAlbums, [serverId]),
            returnValue: _i7.Stream<List<_i2.Album>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Album>>.empty(),
          )
          as _i7.Stream<List<_i2.Album>>);

  @override
  _i7.Future<List<_i2.Album>> getAllAlbums(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlbums, [serverId]),
            returnValue: _i7.Future<List<_i2.Album>>.value(<_i2.Album>[]),
            returnValueForMissingStub: _i7.Future<List<_i2.Album>>.value(
              <_i2.Album>[],
            ),
          )
          as _i7.Future<List<_i2.Album>>);

  @override
  _i7.Future<void> upsertAlbums(List<_i2.Album>? albums, DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#upsertAlbums, [albums, now]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> replaceAlbumList(
    String? serverId,
    _i10.AlbumListQuery? query,
    List<String>? albumIds,
    DateTime? now,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAlbumList, [
              serverId,
              query,
              albumIds,
              now,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> albumListFetchedAt(
    String? serverId,
    _i10.AlbumListQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#albumListFetchedAt, [serverId, query]),
            returnValue: _i7.Future<DateTime?>.value(),
            returnValueForMissingStub: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Future<List<(String, String)>> cachedAlbumLists(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#cachedAlbumLists, [serverId]),
            returnValue: _i7.Future<List<(String, String)>>.value(
              <(String, String)>[],
            ),
            returnValueForMissingStub: _i7.Future<List<(String, String)>>.value(
              <(String, String)>[],
            ),
          )
          as _i7.Future<List<(String, String)>>);

  @override
  _i7.Stream<List<_i2.Song>> watchAlbumSongs(
    String? serverId,
    String? albumId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchAlbumSongs, [serverId, albumId]),
            returnValue: _i7.Stream<List<_i2.Song>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Song>>.empty(),
          )
          as _i7.Stream<List<_i2.Song>>);

  @override
  _i7.Stream<_i2.Song?> watchSong(String? serverId, String? songId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSong, [serverId, songId]),
            returnValue: _i7.Stream<_i2.Song?>.empty(),
            returnValueForMissingStub: _i7.Stream<_i2.Song?>.empty(),
          )
          as _i7.Stream<_i2.Song?>);

  @override
  _i7.Stream<List<_i2.Song>> watchSongsByIds(
    String? serverId,
    List<String>? ids,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSongsByIds, [serverId, ids]),
            returnValue: _i7.Stream<List<_i2.Song>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Song>>.empty(),
          )
          as _i7.Stream<List<_i2.Song>>);

  @override
  _i7.Stream<List<_i2.Song>> searchSongs(
    String? serverId,
    String? term,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchSongs, [serverId, term, limit]),
            returnValue: _i7.Stream<List<_i2.Song>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Song>>.empty(),
          )
          as _i7.Stream<List<_i2.Song>>);

  @override
  _i7.Future<DateTime?> artistAlbumsFetchedAt(
    String? serverId,
    String? artistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#artistAlbumsFetchedAt, [serverId, artistId]),
            returnValue: _i7.Future<DateTime?>.value(),
            returnValueForMissingStub: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Future<int> cachedArtistAlbumCount(String? serverId, String? artistId) =>
      (super.noSuchMethod(
            Invocation.method(#cachedArtistAlbumCount, [serverId, artistId]),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> upsertSongs(List<_i2.Song>? songs, DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSongs, [songs, now]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> albumDetailFetchedAt(
    String? serverId,
    String? albumId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#albumDetailFetchedAt, [serverId, albumId]),
            returnValue: _i7.Future<DateTime?>.value(),
            returnValueForMissingStub: _i7.Future<DateTime?>.value(),
          )
          as _i7.Future<DateTime?>);

  @override
  _i7.Future<int> cachedAlbumSongCount(String? serverId, String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#cachedAlbumSongCount, [serverId, albumId]),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Stream<List<_i2.Playlist>> watchPlaylists(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPlaylists, [serverId]),
            returnValue: _i7.Stream<List<_i2.Playlist>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<_i2.Playlist>>.empty(),
          )
          as _i7.Stream<List<_i2.Playlist>>);

  @override
  _i7.Future<void> upsertPlaylists(
    List<_i2.Playlist>? playlists,
    DateTime? now,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPlaylists, [playlists, now]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setFavorite(
    String? serverId,
    _i10.EntityRef? ref, {
    required bool? favorite,
    required DateTime? now,
    bool? dirty = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setFavorite,
              [serverId, ref],
              {#favorite: favorite, #now: now, #dirty: dirty},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setRating(
    String? serverId,
    _i10.EntityRef? ref, {
    required int? rating,
    bool? dirty = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setRating,
              [serverId, ref],
              {#rating: rating, #dirty: dirty},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reconcileFavorites(
    String? serverId, {
    required Set<String>? artistIds,
    required Set<String>? albumIds,
    required Set<String>? songIds,
    required DateTime? now,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reconcileFavorites,
              [serverId],
              {
                #artistIds: artistIds,
                #albumIds: albumIds,
                #songIds: songIds,
                #now: now,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.PendingWrite>> pendingWrites(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#pendingWrites, [serverId]),
            returnValue: _i7.Future<List<_i9.PendingWrite>>.value(
              <_i9.PendingWrite>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i9.PendingWrite>>.value(
              <_i9.PendingWrite>[],
            ),
          )
          as _i7.Future<List<_i9.PendingWrite>>);

  @override
  _i7.Future<String?> syncValue(String? serverId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#syncValue, [serverId, key]),
            returnValue: _i7.Future<String?>.value(),
            returnValueForMissingStub: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> putSyncValue(
    String? serverId,
    String? key,
    String? value,
    DateTime? now,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#putSyncValue, [serverId, key, value, now]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteServer(String? serverId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteServer, [serverId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> collectGarbage(String? serverId, DateTime? before) =>
      (super.noSuchMethod(
            Invocation.method(#collectGarbage, [serverId, before]),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}

/// A class which mocks [BaseCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseCacheManager extends _i1.Mock implements _i11.BaseCacheManager {
  @override
  _i7.Future<_i3.File> getSingleFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSingleFile,
              [url],
              {#key: key, #headers: headers},
            ),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #getSingleFile,
                  [url],
                  {#key: key, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #getSingleFile,
                  [url],
                  {#key: key, #headers: headers},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Stream<_i4.FileInfo> getFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
            returnValue: _i7.Stream<_i4.FileInfo>.empty(),
            returnValueForMissingStub: _i7.Stream<_i4.FileInfo>.empty(),
          )
          as _i7.Stream<_i4.FileInfo>);

  @override
  _i7.Stream<_i12.FileResponse> getFileStream(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileStream,
              [url],
              {#key: key, #headers: headers, #withProgress: withProgress},
            ),
            returnValue: _i7.Stream<_i12.FileResponse>.empty(),
            returnValueForMissingStub: _i7.Stream<_i12.FileResponse>.empty(),
          )
          as _i7.Stream<_i12.FileResponse>);

  @override
  _i7.Future<_i4.FileInfo> downloadFile(
    String? url, {
    String? key,
    Map<String, String>? authHeaders,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [url],
              {#key: key, #authHeaders: authHeaders, #force: force},
            ),
            returnValue: _i7.Future<_i4.FileInfo>.value(
              _FakeFileInfo_8(
                this,
                Invocation.method(
                  #downloadFile,
                  [url],
                  {#key: key, #authHeaders: authHeaders, #force: force},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i4.FileInfo>.value(
              _FakeFileInfo_8(
                this,
                Invocation.method(
                  #downloadFile,
                  [url],
                  {#key: key, #authHeaders: authHeaders, #force: force},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.FileInfo>);

  @override
  _i7.Future<_i4.FileInfo?> getFileFromCache(
    String? key, {
    bool? ignoreMemCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileFromCache,
              [key],
              {#ignoreMemCache: ignoreMemCache},
            ),
            returnValue: _i7.Future<_i4.FileInfo?>.value(),
            returnValueForMissingStub: _i7.Future<_i4.FileInfo?>.value(),
          )
          as _i7.Future<_i4.FileInfo?>);

  @override
  _i7.Future<_i4.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getFileFromMemory, [key]),
            returnValue: _i7.Future<_i4.FileInfo?>.value(),
            returnValueForMissingStub: _i7.Future<_i4.FileInfo?>.value(),
          )
          as _i7.Future<_i4.FileInfo?>);

  @override
  _i7.Future<_i3.File> putFile(
    String? url,
    _i13.Uint8List? fileBytes, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFile,
              [url, fileBytes],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #putFile,
                  [url, fileBytes],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #putFile,
                  [url, fileBytes],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Future<_i3.File> putFileStream(
    String? url,
    _i7.Stream<List<int>>? source, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFileStream,
              [url, source],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #putFileStream,
                  [url, source],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #putFileStream,
                  [url, source],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Future<void> removeFile(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeFile, [key]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> emptyCache() =>
      (super.noSuchMethod(
            Invocation.method(#emptyCache, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [FileInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileInfo extends _i1.Mock implements _i4.FileInfo {
  @override
  _i3.File get file =>
      (super.noSuchMethod(
            Invocation.getter(#file),
            returnValue: _FakeFile_7(this, Invocation.getter(#file)),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.getter(#file),
            ),
          )
          as _i3.File);

  @override
  _i4.FileSource get source =>
      (super.noSuchMethod(
            Invocation.getter(#source),
            returnValue: _i4.FileSource.NA,
            returnValueForMissingStub: _i4.FileSource.NA,
          )
          as _i4.FileSource);

  @override
  DateTime get validTill =>
      (super.noSuchMethod(
            Invocation.getter(#validTill),
            returnValue: _FakeDateTime_9(this, Invocation.getter(#validTill)),
            returnValueForMissingStub: _FakeDateTime_9(
              this,
              Invocation.getter(#validTill),
            ),
          )
          as DateTime);

  @override
  int get statusCode =>
      (super.noSuchMethod(
            Invocation.getter(#statusCode),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get originalUrl =>
      (super.noSuchMethod(
            Invocation.getter(#originalUrl),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#originalUrl),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#originalUrl),
            ),
          )
          as String);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i3.File {
  @override
  _i3.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_7(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i3.File);

  @override
  _i3.FileSystem get fileSystem =>
      (super.noSuchMethod(
            Invocation.getter(#fileSystem),
            returnValue: _FakeFileSystem_10(
              this,
              Invocation.getter(#fileSystem),
            ),
            returnValueForMissingStub: _FakeFileSystem_10(
              this,
              Invocation.getter(#fileSystem),
            ),
          )
          as _i3.FileSystem);

  @override
  String get basename =>
      (super.noSuchMethod(
            Invocation.getter(#basename),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#basename),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#basename),
            ),
          )
          as String);

  @override
  String get dirname =>
      (super.noSuchMethod(
            Invocation.getter(#dirname),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#dirname),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#dirname),
            ),
          )
          as String);

  @override
  _i3.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_11(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_11(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i3.Directory);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_5(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_5(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<_i3.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Future<_i3.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i3.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_7(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i3.File);

  @override
  _i7.Future<_i3.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i3.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_7(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_7(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i3.File);

  @override
  _i7.Future<_i3.File> writeAsBytes(
    List<int>? bytes, {
    _i5.FileMode? mode = _i5.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Future<_i3.File> writeAsString(
    String? contents, {
    _i5.FileMode? mode = _i5.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.File>.value(
              _FakeFile_7(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.File>);

  @override
  _i7.Future<_i3.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i7.Future<_i3.FileSystemEntity>.value(
              _FakeFileSystemEntity_12(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.FileSystemEntity>.value(
              _FakeFileSystemEntity_12(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i7.Future<_i3.FileSystemEntity>);

  @override
  _i7.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i7.Future<_i5.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i7.Future<_i5.FileStat>.value(
              _FakeFileStat_13(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i7.Future<_i5.FileStat>.value(
              _FakeFileStat_13(this, Invocation.method(#stat, [])),
            ),
          )
          as _i7.Future<_i5.FileStat>);

  @override
  _i5.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_13(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_13(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i5.FileStat);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<_i5.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i7.Stream<_i5.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i7.Stream<_i5.FileSystemEvent>.empty(),
          )
          as _i7.Stream<_i5.FileSystemEvent>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i7.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i7.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i7.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_9(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_9(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i7.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i7.Future<dynamic>.value(),
            returnValueForMissingStub: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i7.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i7.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i7.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_9(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_9(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i7.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i7.Future<dynamic>.value(),
            returnValueForMissingStub: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i5.RandomAccessFile> open({
    _i5.FileMode? mode = _i5.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i7.Future<_i5.RandomAccessFile>.value(
              _FakeRandomAccessFile_14(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i5.RandomAccessFile>.value(
              _FakeRandomAccessFile_14(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i7.Future<_i5.RandomAccessFile>);

  @override
  _i5.RandomAccessFile openSync({_i5.FileMode? mode = _i5.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_14(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_14(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i5.RandomAccessFile);

  @override
  _i7.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i7.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i7.Stream<List<int>>.empty(),
          )
          as _i7.Stream<List<int>>);

  @override
  _i5.IOSink openWrite({
    _i5.FileMode? mode = _i5.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_15(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_15(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i5.IOSink);

  @override
  _i7.Future<_i13.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i7.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
            returnValueForMissingStub: _i7.Future<_i13.Uint8List>.value(
              _i13.Uint8List(0),
            ),
          )
          as _i7.Future<_i13.Uint8List>);

  @override
  _i13.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i13.Uint8List(0),
            returnValueForMissingStub: _i13.Uint8List(0),
          )
          as _i13.Uint8List);

  @override
  _i7.Future<String> readAsString({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  String readAsStringSync({_i15.Encoding? encoding = const _i15.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i7.Future<List<String>> readAsLines({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i5.FileMode? mode = _i5.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  void writeAsStringSync(
    String? contents, {
    _i5.FileMode? mode = _i5.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );
}
